### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-block_percipio_home#5]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin appears to integrate with an external service (percipio) so privacy api compliance is a blocker for plugins db approval.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by skillsoftadmin** [comment]
Hi, Dan Marsden,
Appreciate your review. could you please re-review it once, we have implemented the Privacy API
Thanks!

**Comment by danmarsden** [comment]
@skillsoftadmin - please update the entry in the moodl.org plugins db with your new version and hit the "Request re-approval" button to add it back to our review queue when you are ready for us to take another look at this. Thanks!

**Comment by danmarsden** [comment]
looks like you've got a mess of branches here in github and the "default" branch is set to "develop" which doesn't have the privacy api at all... can you please clean up the branches here in github before we look at approving this? (also - please add a comment to the tracker issue: https://tracker.moodle.org/browse/CONTRIB-9106) - you may have to create an account in the moodle tracker if you haven't already.

**Comment by danmarsden** [comment]
Looks like you've fixed the develop branch up to have the privacy api but it's still not clear to a user which branch is your active branch/should be used...

"main" doesn't have the privacy api... "develop" does - the branch name "develop" is likely to scare off some people thinking that it's not a stable branch. As mentioned, can you please add some detail to your readme file to make it clear which branch people should be using and if "develop" is in fact a "stable/production ready" branch?

thanks,

**Comment by skillsoftadmin** [comment]
Hi @danmarsden , could you please have a look at the repository.
I have cleaned up the branches and we have incorporated the comments.

**Comment by danmarsden** [comment]
thanks! - hopefully that might keep confusing people! :-)
